name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }]
  push: { branches: ["main"] }
  workflow_dispatch:
jobs:
  contributions:
    runs-on: ubuntu-latest
    steps:
      - name: Contributions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.notable.svg
          token: ${{ secrets.METRICS }}
          base: ""
          plugin_notable: "yes"

  iso-calender:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: iso-calender.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Runope
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

  languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Runope
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_languages: yes

  stargazers:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: stargazers.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Runope
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_stargazers: yes

  wakatime:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: wakatime.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Runope
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 14
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os

  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Runope
          template: classic
          base: ""
          config_timezone: Asia/Shanghai
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: push, issue, pr, release, review, wiki, member, comment

  metadata:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metadata.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: Runope
          template: classic
          base: metadata
          config_timezone: Asia/Shanghai
  code:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: code.svg
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories
          token: ${{ secrets.METRICS }}

          # Options
          user: runope
          template: classic
          base: ""
          config_display: large
          config_octicon: yes
          config_timezone: Asia/Shanghai
          plugin_code: yes
          plugin_code_days: 5
          plugin_code_lines: 30
          plugin_code_load: 400
          plugin_code_visibility: public
  reward:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          filename: reward.svg
          # Options
          user: runope
          template: classic
          base: ""
          config_display: large
          config_octicon: yes
          config_timezone: Asia/Shanghai
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
